In [1]:
import numpy as np
from numpy.linalg import eig

In [2]:
A = np.array([[6,5],[2,3],[1,4]])
A

array([[6, 5],
       [2, 3],
       [1, 4]])

In [3]:
M = np.mean(A,axis=0)
M

array([3., 4.])

In [4]:
#Standardise the values
C = A - M
print(C)

[[ 3.  1.]
 [-1. -1.]
 [-2.  0.]]


In [5]:
#Calculate covariance matrix of each feature
V = np.cov(C.T)
V

array([[7., 2.],
       [2., 1.]])

In [6]:
#Eigen vectors of covariance matrix
values,vectors = eig(V)
print(values)

[7.60555128 0.39444872]


In [7]:
print(vectors)

[[ 0.95709203 -0.28978415]
 [ 0.28978415  0.95709203]]


In [8]:
#Project the data
P = np.dot(C,vectors)

In [9]:
P

array([[ 3.16106023,  0.08773958],
       [-1.24687618, -0.66730788],
       [-1.91418405,  0.5795683 ]])